# Generated by Django 5.1.4 on 2025-04-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('diplom_number', models.CharField(max_length=50)),
                ('graduation_year', models.PositiveIntegerField()),
                ('degree_level', models.CharField(choices=[('school', 'Maktab'), ('college', 'Kollej'), ('university', 'Universitet'), ('other', 'Boshqa')], default='college', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('passport_series', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('given_by', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.region')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('regular', '1-kurs (yangi qabul)'), ('transfer', 'Perevod (o‘qishni ko‘chirish)')], default='regular', max_length=20)),
                ('study_year', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Yuborilgan'), ('review', 'Ko‘rib chiqilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tuition_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.tuitionfee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diplom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.diplominfo')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='applications.passportinfo')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='applications.region'),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/documents/')),
                ('doc_type', models.CharField(help_text='Masalan: pasport, diplom, rasm', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
    ]
