# Generated by Django 5.1.4 on 2025-04-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/passport/'),
        ),
    ]
