# Generated by Django 5.1.4 on 2025-04-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_passportinfo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
