# Generated by Django 5.1.4 on 2025-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_delete_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplominfo',
            name='diplom_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/diploms/'),
        ),
    ]
