# Generated by Django 5.1.4 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_phoneverification_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
