# Generated by Django 5.1.4 on 2025-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
    ]
